### PR TITLE
Only push to docker hub on default branch

### PR DESCRIPTION
**Pull request by blyme**

### CODE REVIEW

**Review by danquah — APPROVED** [review]
I just verified that the workflow did not push and it seems to work!

**Comment by xendk** [comment]
Question: Didn't the `if` on the workflow work?

I think it's unfortunate that the workflow is named "Docker build and push" when in fact it's not pushing most of the time.

**Comment by danquah** [comment]
> Question: Didn't the if on the workflow work?

[No](https://github.com/reload/drupal-apache-fpm/runs/6725914111?check_suite_focus=true#step:7:816) 

> I think it's unfortunate that the workflow is named "Docker build and push" when in fact it's not pushing most of the time.

You have a point there, I would not argue against changing it :)

**Comment by xendk** [comment]
> No

Interesting... It shouldn't, obviously. Maybe it choked on the syntax?

> When you use expressions in an if conditional, you may omit the expression syntax (${{ }}) because GitHub automatically evaluates the if conditional as an expression. For more information, see "[Expressions](https://docs.github.com/en/actions/learn-github-actions/expressions)."

> You have a point there, I would not argue against changing it :)

Would be nicest with separate "Build" and "Push" jobs, but as they're isolated that wont work. Best idea I can come up with is two virtually identical workflows with different names... Unless expression syntax works in `name`?

**Comment by danquah** [comment]
> Unless expression syntax works in name?

It does in azure DevOps pipelines - and the two gets more and more similar as time progresses so it may very well work.

**Comment by danquah** [comment]
But - we could also just name it "Build. Publish on merge" or something like that. I do prefer not having two separate instances of the action that we have to keep in sync.

**Comment by xendk** [comment]
We can... But the expression hack is cooler.

**Comment by xendk** [comment]
(and have the advantage of telling when it pushed)

**Pull request merged**
